name: Server Deploy to EC2

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'beat-forge/**'

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Change directory and build
      run: |
        cd beat-forge
        docker build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t imizik/forge-server:latest .

    - name: Push Docker image
      run: docker push imizik/forge-server:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull imizik/forge-server:latest
          docker stop forge-server
          docker rm forge-server
          docker run -d -p 8080:8080 --name forge-server imizik/forge-server:latest
